#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
build_web_data_from_here.py

Run this file from the root of your TAMC project:

    C:\Users\PC\Desktop\tamcsismico

It creates a clean web folder:

    web_data/latest/

The output keeps the SAME structure expected by the Streamlit app:

    web_data/latest/<REGION>/mainshock/plots/*.png
    web_data/latest/<REGION>/fixed_stations.json
    web_data/latest/<REGION>/mainshock/network_summary.json
    web_data/latest/network_global_summary.json
    web_data/latest/manifest.json

Sources:
- PNG figures are copied from:
    resultados/<REGION>/mainshock/plots/

- fixed_stations.json is copied from:
    data/<REGION>/fixed_stations.json
    or fallback paths inside resultados/

- network_summary.json is copied from:
    resultados/<REGION>/mainshock/network_summary.json

- network_global_summary.json is copied from:
    resultados/network_global_summary.json

This folder can then be uploaded/synced to GitHub for Streamlit.
"""

from __future__ import annotations

import json
import re
import shutil
from pathlib import Path
from datetime import datetime, timezone


# ============================================================
# PATHS RELATIVE TO THIS FILE
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parent

# PNGs + network summaries generated by the analysis pipeline
RESULTADOS_DIR = PROJECT_ROOT / "resultados"

# Station metadata generated by the download/monitor pipeline
DATA_DIR = PROJECT_ROOT / "data"

# Lightweight web output
WEB_DIR = PROJECT_ROOT / "web_data" / "latest"

IMAGE_EXTENSIONS = {".png"}
CLEAN_WEB_DIR = True
ONLY_RECENT = True

GLOBAL_NETWORK_SUMMARY_NAME = "network_global_summary.json"
REGION_NETWORK_SUMMARY_NAME = "network_summary.json"


# ============================================================
# HELPERS
# ============================================================

def safe_name(name: str) -> str:
    """Create a filesystem-safe folder name without changing the event identity."""
    name = name.replace(" ", "_")
    name = re.sub(r"[^A-Za-z0-9_.\-\(\)]+", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")
    return name[:180]


def is_recent_folder(folder: Path) -> bool:
    """Return True if folder should be included."""
    if not ONLY_RECENT:
        return True
    return "RECENT" in folder.name.upper()


def list_result_region_folders() -> list[Path]:
    """List monitored region folders in resultados/."""
    if not RESULTADOS_DIR.exists():
        raise FileNotFoundError(f"RESULTADOS_DIR does not exist: {RESULTADOS_DIR}")

    folders = [p for p in RESULTADOS_DIR.iterdir() if p.is_dir() and is_recent_folder(p)]
    return sorted(folders, key=lambda p: p.name.lower())


def matching_data_region(result_region: Path) -> Path | None:
    """
    Find the corresponding folder in data/.

    Usually:
        resultados/<REGION_NAME>
        data/<REGION_NAME>

    have identical names.
    """
    if not DATA_DIR.exists():
        return None

    exact = DATA_DIR / result_region.name
    if exact.exists() and exact.is_dir():
        return exact

    # Fallback: match by prefix before _RECENT_
    key = result_region.name.lower().split("_recent_")[0]
    for d in DATA_DIR.iterdir():
        if d.is_dir() and d.name.lower().split("_recent_")[0] == key:
            return d

    return None


def copy_plots_preserving_structure(result_region: Path, dst_region: Path) -> int:
    """
    Copy PNG figures while preserving the expected structure:

        <REGION>/mainshock/plots/*.png
    """
    src_plots = result_region / "mainshock" / "plots"
    dst_plots = dst_region / "mainshock" / "plots"

    if not src_plots.exists() or not src_plots.is_dir():
        print(f"[WARN] Missing plots folder: {src_plots}")
        return 0

    dst_plots.mkdir(parents=True, exist_ok=True)

    count = 0
    for img in sorted(src_plots.iterdir()):
        if img.is_file() and img.suffix.lower() in IMAGE_EXTENSIONS:
            shutil.copy2(img, dst_plots / img.name)
            count += 1

    return count


def copy_fixed_stations(result_region: Path, dst_region: Path) -> bool:
    """
    Copy fixed_stations.json from data/<REGION>/ to web_data/latest/<REGION>/.
    """
    data_region = matching_data_region(result_region)

    candidates: list[Path] = []

    if data_region is not None:
        candidates.extend([
            data_region / "fixed_stations.json",
            data_region / "mainshock" / "fixed_stations.json",
        ])
        candidates.extend(data_region.rglob("fixed_stations.json"))

    # Fallback: if later you copy it into resultados as well
    candidates.extend([
        result_region / "fixed_stations.json",
        result_region / "mainshock" / "fixed_stations.json",
    ])
    candidates.extend(result_region.rglob("fixed_stations.json"))

    seen: set[Path] = set()
    for js in candidates:
        try:
            js = js.resolve()
            if js in seen:
                continue
            seen.add(js)

            if js.exists() and js.is_file():
                dst_region.mkdir(parents=True, exist_ok=True)
                shutil.copy2(js, dst_region / "fixed_stations.json")
                return True
        except Exception:
            continue

    return False


def copy_network_summary(result_region: Path, dst_region: Path) -> bool:
    """
    Copy the per-region network_summary.json generated by generate_network_summaries.py.

    Source:
        resultados/<REGION>/mainshock/network_summary.json

    Destination:
        web_data/latest/<REGION>/mainshock/network_summary.json
    """
    src = result_region / "mainshock" / REGION_NETWORK_SUMMARY_NAME
    dst = dst_region / "mainshock" / REGION_NETWORK_SUMMARY_NAME

    if not src.exists() or not src.is_file():
        return False

    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return True


def copy_global_network_summary(web_dir: Path) -> bool:
    """
    Copy the global summary generated by generate_network_summaries.py.

    Source:
        resultados/network_global_summary.json

    Destination:
        web_data/latest/network_global_summary.json
    """
    src = RESULTADOS_DIR / GLOBAL_NETWORK_SUMMARY_NAME
    dst = web_dir / GLOBAL_NETWORK_SUMMARY_NAME

    if not src.exists() or not src.is_file():
        return False

    web_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return True


def read_json_safely(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def extract_region_summary_status(dst_region: Path) -> dict:
    """
    Read copied network_summary.json and extract a few UI-friendly manifest fields.
    """
    js = dst_region / "mainshock" / REGION_NETWORK_SUMMARY_NAME
    data = read_json_safely(js)
    if not data:
        return {
            "network_summary_readable": False,
            "network_state": None,
            "descriptive_score_0_100": None,
            "descriptive_score_level": None,
            "schema_version": None,
        }

    interp = data.get("joint_interpretation") or data.get("interpretation") or {}
    return {
        "network_summary_readable": True,
        "network_state": interp.get("network_state"),
        "descriptive_score_0_100": interp.get("descriptive_score_0_100"),
        "descriptive_score_level": interp.get("descriptive_score_level"),
        "schema_version": data.get("schema_version"),
    }


def write_manifest(web_dir: Path, rows: list[dict], has_global_summary: bool) -> None:
    """Write a small JSON manifest for traceability."""
    manifest = {
        "generated_utc": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        "project_root": str(PROJECT_ROOT),
        "source_resultados_dir": str(RESULTADOS_DIR),
        "source_data_dir": str(DATA_DIR),
        "web_dir": str(WEB_DIR),
        "structure": (
            "<REGION>/mainshock/plots/*.png + "
            "<REGION>/fixed_stations.json + "
            "<REGION>/mainshock/network_summary.json + "
            "network_global_summary.json"
        ),
        "global_network_summary_json": has_global_summary,
        "regions": rows,
    }

    with open(web_dir / "manifest.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)


# ============================================================
# MAIN
# ============================================================

def main() -> int:
    print("=" * 70)
    print("TAMC WEB DATA BUILDER")
    print("=" * 70)
    print(f"Project root : {PROJECT_ROOT}")
    print(f"PNG source   : {RESULTADOS_DIR}")
    print(f"JSON source  : {DATA_DIR}")
    print(f"Output web   : {WEB_DIR}")
    print("=" * 70)

    if CLEAN_WEB_DIR and WEB_DIR.exists():
        print(f"[CLEAN] Removing old folder: {WEB_DIR}")
        shutil.rmtree(WEB_DIR)

    WEB_DIR.mkdir(parents=True, exist_ok=True)

    result_regions = list_result_region_folders()

    if not result_regions:
        print(f"[WARN] No RECENT region folders found in: {RESULTADOS_DIR}")
        return 1

    rows: list[dict] = []

    for result_region in result_regions:
        dst_name = safe_name(result_region.name)
        dst_region = WEB_DIR / dst_name

        n_png = copy_plots_preserving_structure(result_region, dst_region)
        has_fixed_stations = copy_fixed_stations(result_region, dst_region)
        has_network_summary = copy_network_summary(result_region, dst_region)

        if n_png == 0 and not has_fixed_stations and not has_network_summary:
            shutil.rmtree(dst_region, ignore_errors=True)
            print(
                f"[SKIP] {result_region.name} | "
                f"PNG=0 | fixed_stations.json=no | network_summary.json=no"
            )
            continue

        summary_status = extract_region_summary_status(dst_region)

        rows.append({
            "source_resultados_folder": result_region.name,
            "web_folder": dst_name,
            "png_files": n_png,
            "fixed_stations_json": has_fixed_stations,
            "network_summary_json": has_network_summary,
            **summary_status,
        })

        print(
            f"[OK] {result_region.name} -> web_data/latest/{dst_name} | "
            f"PNG={n_png} | "
            f"fixed_stations.json={'yes' if has_fixed_stations else 'no'} | "
            f"network_summary.json={'yes' if has_network_summary else 'no'} | "
            f"state={summary_status.get('network_state')} | "
            f"score={summary_status.get('descriptive_score_0_100')}"
        )

    has_global_summary = copy_global_network_summary(WEB_DIR)
    write_manifest(WEB_DIR, rows, has_global_summary)

    print("=" * 70)
    print(f"[DONE] Web data created: {WEB_DIR}")
    print(f"[DONE] Regions copied: {len(rows)}")
    print(f"[DONE] Global network summary: {'yes' if has_global_summary else 'no'}")
    print("=" * 70)

    if not has_global_summary:
        print(
            "[WARN] resultados/network_global_summary.json was not found. "
            "Run generate_network_summaries.py before this builder if you want global interpretation in the app."
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
